/*
 * GA4GH service-info API specification
 *
 * A way for a service to describe basic metadata concerning a service alongside a set of capabilities and/or limitations of the service. More information on [GitHub](https://github.com/ga4gh-discovery/ga4gh-service-info/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ga4gh-discovery-networks@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */

use crate::serviceinfo::models;

/// ServiceType : Type of a GA4GH service
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceType {
    /// Namespace in reverse domain name format. Use `org.ga4gh` for implementations compliant with official GA4GH specifications. For services with custom APIs not standardized by GA4GH, or implementations diverging from official GA4GH specifications, use a different namespace (e.g. your organization's reverse domain name).
    #[serde(rename = "group")]
    pub group: String,
    /// Name of the API or GA4GH specification implemented. Official GA4GH types should be assigned as part of standards approval process. Custom artifacts are supported.
    #[serde(rename = "artifact")]
    pub artifact: String,
    /// Version of the API or specification. GA4GH specifications use semantic versioning.
    #[serde(rename = "version")]
    pub version: String,
}

impl ServiceType {
    /// Type of a GA4GH service
    pub fn new(group: String, artifact: String, version: String) -> ServiceType {
        ServiceType {
            group,
            artifact,
            version,
        }
    }
}

