/*
 * GA4GH service-info API specification
 *
 * A way for a service to describe basic metadata concerning a service alongside a set of capabilities and/or limitations of the service. More information on [GitHub](https://github.com/ga4gh-discovery/ga4gh-service-info/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ga4gh-discovery-networks@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]
#![allow(clippy::empty_docs)]
use crate::serviceinfo::models;
use serde::{Deserialize, Serialize};

/// ServiceOrganization : Organization providing the service
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceOrganization {
    /// Name of the organization responsible for the service
    #[serde(rename = "name")]
    pub name: String,
    /// URL of the website of the organization (RFC 3986 format)
    #[serde(rename = "url")]
    pub url: String,
}

impl ServiceOrganization {
    /// Organization providing the service
    pub fn new(name: String, url: String) -> ServiceOrganization {
        ServiceOrganization {
            name,
            url,
        }
    }
}

