FROM ubuntu:22.04

RUN apt update && \
    apt install -y --no-install-recommends \
    curl \
    default-jdk && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Ref.: https://nodejs.org/en/download/package-manager
ENV NVM_DIR=/root/.nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash && \
    . "$NVM_DIR/nvm.sh" && \
    nvm install 22.11.0 && \
    nvm alias default 22.11.0 && \
    nvm use default

ENV PATH=$NVM_DIR/versions/node/v22.11.0/bin:$PATH

WORKDIR /app

# Note: Not working...
# RUN npm install -g @openapitools/openapi-generator-cli
