/*
 * GA4GH Tool Discovery API
 *
 * Proposed API for GA4GH (Global Alliance for Genomics & Health) tool repositories. A tool consists of a set of container images that are paired with a set of documents. Examples of documents include CWL (Common Workflow Language), WDL (Workflow Description Language), NFL (Nextflow), GXFORMAT2 (Galaxy) or SMK (Snakemake) that describe how to use those images and a set of specifications for those images (examples are Dockerfiles or Singularity recipes) that describe how to reproduce those images in the future. We use the following terminology, a \"container image\" describes a container as stored at rest on a filesystem, a \"tool\" describes one of the triples as described above. In practice, examples of \"tools\" include CWL CommandLineTools, CWL Workflows, WDL workflows, and Nextflow workflows that reference containers in formats such as Docker or Singularity.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]
#![allow(clippy::empty_docs)]
use crate::clients::trs::models;
use serde::{Deserialize, Serialize};

/// DescriptorType : The type of descriptor that represents this version of the tool. Note that these files can also include associated Docker/container files  and test parameters that further describe a version of a tool.
/// The type of descriptor that represents this version of the tool. Note that these files can also include associated Docker/container files  and test parameters that further describe a version of a tool.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DescriptorType {
    #[serde(rename = "CWL")]
    Cwl,
    #[serde(rename = "WDL")]
    Wdl,
    #[serde(rename = "NFL")]
    Nfl,
    #[serde(rename = "GALAXY")]
    Galaxy,
    #[serde(rename = "SMK")]
    Smk,

}

impl std::fmt::Display for DescriptorType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Cwl => write!(f, "CWL"),
            Self::Wdl => write!(f, "WDL"),
            Self::Nfl => write!(f, "NFL"),
            Self::Galaxy => write!(f, "GALAXY"),
            Self::Smk => write!(f, "SMK"),
        }
    }
}

impl Default for DescriptorType {
    fn default() -> DescriptorType {
        Self::Cwl
    }
}

