/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]
#![allow(clippy::empty_docs)]
use crate::clients::drs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkAccessUrl {
    #[serde(rename = "drs_object_id", skip_serializing_if = "Option::is_none")]
    pub drs_object_id: Option<String>,
    #[serde(rename = "drs_access_id", skip_serializing_if = "Option::is_none")]
    pub drs_access_id: Option<String>,
    /// A fully resolvable URL that can be used to fetch the actual object bytes.
    #[serde(rename = "url")]
    pub url: String,
    /// An optional list of headers to include in the HTTP request to `url`. These headers can be used to provide auth tokens required to fetch the object bytes.
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<Vec<String>>,
}

impl BulkAccessUrl {
    pub fn new(url: String) -> BulkAccessUrl {
        BulkAccessUrl {
            drs_object_id: None,
            drs_access_id: None,
            url,
            headers: None,
        }
    }
}

