/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]
#![allow(clippy::empty_docs)]
use crate::clients::drs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DrsService {
    /// The max length the bullk request endpoints can handle (>= 1) before generating a 413 error e.g. how long can the arrays bulk_object_ids and bulk_object_access_ids be for this server.
    #[serde(rename = "maxBulkRequestLength")]
    pub max_bulk_request_length: i32,
    #[serde(rename = "type")]
    pub r#type: Box<models::DrsServiceType>,
}

impl DrsService {
    pub fn new(max_bulk_request_length: i32, r#type: models::DrsServiceType) -> DrsService {
        DrsService {
            max_bulk_request_length,
            r#type: Box::new(r#type),
        }
    }
}

