/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]
#![allow(clippy::empty_docs)]
use crate::clients::drs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DrsServiceType {
    #[serde(rename = "artifact")]
    pub artifact: Artifact,
}

impl DrsServiceType {
    pub fn new(artifact: Artifact) -> DrsServiceType {
        DrsServiceType {
            artifact,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Artifact {
    #[serde(rename = "drs")]
    Drs,
}

impl Default for Artifact {
    fn default() -> Artifact {
        Self::Drs
    }
}

