/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]
#![allow(clippy::empty_docs)]
use crate::clients::drs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptionsBulkObject200Response {
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Box<models::Summary>>,
    /// Error codes for each unresolved drs objects.
    #[serde(rename = "unresolved_drs_objects", skip_serializing_if = "Option::is_none")]
    pub unresolved_drs_objects: Option<Vec<models::UnresolvedInner>>,
    #[serde(rename = "resolved_drs_object", skip_serializing_if = "Option::is_none")]
    pub resolved_drs_object: Option<Vec<models::Authorizations>>,
}

impl OptionsBulkObject200Response {
    pub fn new() -> OptionsBulkObject200Response {
        OptionsBulkObject200Response {
            summary: None,
            unresolved_drs_objects: None,
            resolved_drs_object: None,
        }
    }
}

