/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]
#![allow(clippy::empty_docs)]
use crate::clients::drs::models;
use serde::{Deserialize, Serialize};

/// ServiceType : Type of a GA4GH service
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceType {
    /// Namespace in reverse domain name format. Use `org.ga4gh` for implementations compliant with official GA4GH specifications. For services with custom APIs not standardized by GA4GH, or implementations diverging from official GA4GH specifications, use a different namespace (e.g. your organization's reverse domain name).
    #[serde(rename = "group")]
    pub group: String,
    /// Name of the API or GA4GH specification implemented. Official GA4GH types should be assigned as part of standards approval process. Custom artifacts are supported.
    #[serde(rename = "artifact")]
    pub artifact: String,
    /// Version of the API or specification. GA4GH specifications use semantic versioning.
    #[serde(rename = "version")]
    pub version: String,
}

impl ServiceType {
    /// Type of a GA4GH service
    pub fn new(group: String, artifact: String, version: String) -> ServiceType {
        ServiceType {
            group,
            artifact,
            version,
        }
    }
}

