/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */

#![allow(unused_imports)]
#![allow(clippy::empty_docs)]
use crate::clients::drs::models;
use serde::{Deserialize, Serialize};

/// Summary : A summary of what was resolved.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Summary {
    /// Number of items requested.
    #[serde(rename = "requested", skip_serializing_if = "Option::is_none")]
    pub requested: Option<i32>,
    /// Number of objects resolved.
    #[serde(rename = "resolved", skip_serializing_if = "Option::is_none")]
    pub resolved: Option<i32>,
    /// Number of objects not resolved.
    #[serde(rename = "unresolved", skip_serializing_if = "Option::is_none")]
    pub unresolved: Option<i32>,
}

impl Summary {
    /// A summary of what was resolved.
    pub fn new() -> Summary {
        Summary {
            requested: None,
            resolved: None,
            unresolved: None,
        }
    }
}

